version: "3.8"
services:
  db:
    image: postgres
    container_name: notes-db
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD} 
      POSTGRES_DB: ${DB_DATABASE}
      
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: always
    depends_on: 
      - db
    ports:
      - 8888:80
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD} 

  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    environment: 
      ENV: ${ENV}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}  
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD} 
      DB_DATABASE: ${DB_DATABASE}
    restart: always
    depends_on:
      - db
    ports:
      - 3000:3000
    networks:
      - web

    image: incerto13/notes-api:latest

  nginx:
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - api
    networks:
      - web
networks:
  web:
    driver: bridge
