version: "3.8"
services:
  db:
    image: postgres
    container_name: notes-db_test-int
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test-int
      
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_test-int
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@solace.com
      PGADMIN_DEFAULT_PASSWORD: postgres
